"""Initial_With_Stats

Revision ID: 7ae27421de92
Revises: 
Create Date: 2026-01-17 13:54:17.707508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae27421de92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_t_users_email'), 't_users', ['email'], unique=True)
    op.create_index(op.f('ix_t_users_username'), 't_users', ['username'], unique=True)
    op.create_table('t_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('organizing_team', sa.String(), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('average_duration', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['t_users.uid'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['t_users.uid'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('t_attendance',
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('leave_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['t_events.event_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_attendance')
    op.drop_table('t_events')
    op.drop_index(op.f('ix_t_users_username'), table_name='t_users')
    op.drop_index(op.f('ix_t_users_email'), table_name='t_users')
    op.drop_table('t_users')
    # ### end Alembic commands ###
